### ISSUE TITLE
Write performance benchmark for reading from a big CSV file

### ISSUE THREAD

**Issue by codein-dev** [codeincorp/mongo#18]
Sample dataset can be found here:
- https://github.com/datablist/sample-csv-files
- https://excelbianalytics.com/wp/downloads-18-sample-csv-files-data-sets-for-testing-sales/

Performance benchmark framework:
https://github.com/codeincorp/mongo/blob/master/src/third_party/benchmark/dist/README.md

Benchmark suite example:
https://github.com/codeincorp/mongo/blob/master/src/mongo/bson/bson_bm.cpp

SConscript example:
https://github.com/codeincorp/mongo/blob/master/src/mongo/bson/SConscript#L37

**Comment by MaxJuneKim** [comment]
Done
