### ISSUE TITLE
Add a CSV reader to implement `InputStream`

### ISSUE THREAD

**Issue by codein-dev** [codeincorp/mongo#4]
The CSV file reader will be given the relative path for the metadata file. The metadata file will describe the field names and their types. Its format is as follows:

`fieldName1/type1, fieldName2/type2, ..., fieldNameN/typeN`

The CSV file reader will be given `strict` flag and `threshold` parameters as well.
The `strict` means that data should follow the type in the metadata file and if `strict` is `true` and if the CSV file reader find over # of `threshold` lines do not follow the metadata type info, then it aborts reading process.

Both `strict` and `threshold` parameters are optional and the default value for `strict` is `false`.

**Comment by MaxJuneKim** [comment]
Done
